baseURL = "http://example.org/"
languageCode = "en-us"
publishDir = "docs"
[server]
bind = "0.0.0.0"
title = "My New Hugo Site"
[markup.goldmark.renderer]
  unsafe = true
[[menu.main]]
name = "学校课本"
weight = 1
url = "/school"

[[menu.main]] 
name = "电影字幕"
weight = 1
url = "/movie"